#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+\))?: .+"
if ! echo "$message" | grep -E "$requiredPattern" > /dev/null; then
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "feat: add new feature"
  echo "fix: fix some bug"
  echo "Available types: feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert"
  echo "-"
  exit 1
fi 